apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-dev
  namespace: dev-ns
spec:
  selector:
    matchLabels:
      app: dept-dev
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: dept-dev
    spec:
      containers:
      - name: dept-dev
        image: 778168509800.dkr.ecr.ap-northeast-1.amazonaws.com/dev:number
        resources:
          requests:
            memory: "128Mi"
            cpu: 100m
          limits:
            memory: "256Mi"
            cpu: 1
        ports:
          - containerPort: 80

