apiVersion: v1
kind: Service
metadata:
  name: static-svc
  namespace: prod-ns
spec:
  type: LoadBalancer
  selector:
    app: static-dept
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80




